# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200302_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
